#!/usr/bin/env bash
#FizzBuzz
for i in {1..100}
do
	if [ $(i % 3) == 0 && $(i % 5) == 0 ]
	then 
		echo "FizzBuzz"
		if  (( $i % 3 == 0 ))
	then
		echo "Fizz"
		if (( $i % 5 == 0 ))
	then
		echo "buzz"
	else 
		echo "$i"
	fi
	fi
	fi
done
