#!/usr/bin/env bash
#If 9, say Hi!
num=11

while [ $num -ge 1 ]
do
	  ((num--))
	    if [[ "$num" == '1' ]]; then
		        echo "Hi"
			    continue
			      fi
			        echo "Best School"
				  
			done
