#!/usr/bin/env bash
#If 9, say Hi!
n=0
while [ $n -le 10 ]
do
    # Check the value of n
    if [ $n == 9 ]
    then
        echo "Hi"      
        break
    fi
    echo "Best School"
    (( n++ ))
done
