#!/usr/bin/env bash
#Superstitious numbers
COUNTER=0

while [ $COUNTER -lt 20 ]
do
    case $COUNTER in

        4)
    	    echo $COUNTER
    	    echo "bad luck from China"
    	    ;;
							    	
	9)
	    echo $COUNTER
	    echo "bad luck from Japan"
	    ;;
												    	
    	17)
	    echo $COUNTER
  	    echo "bad luck from Italy"
    	    ;;
    	*)
	    echo $COUNTER
    	    ;;
														        esac
															    let COUNTER+=1
done
