#!/usr/bin/env bash
#process and pid file
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
	echo To infinity and beyond
	sleep 2
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'sudo rm /var/run/myscript.pid exit' SIGQUIT
