#!/usr/bin/env bash
#process and pid file
touch /var/run/myscript.pid
while true 
do
	echo To infinity and beyond
	sleep 2
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	rm /var/run/myscript.pid
done
