#!/usr/bin/env bash
#process and pid file
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
echo To infinity and beyond
	sleep 2
done
	trap 'echo I hate the kill command;rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo Y U no love me?!;exit' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
