#!/usr/bin/env bash
# Manages 'manage_my_process'
if [ "$1" = "start" ]
then
        ./manage_my_process &
	sudo bash -c "echo $$ > /var/run/my_process.pid"
        echo "manage_my_process started"
if [ "$1" = "stop" ]
then
	sudo pkill -f ./manage_my_process
        sudo rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
fi
if [ "$1" = "restart" ]
then
        sudo pkill -f /var/run/my_process.pid
        rm /var/run/my_process.pid
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
else
        echo "Usage: manage_my_process {start|stop|restart}"
fi
